cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
]

ecom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from accounts.views import register


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls',namespace='cart')),
    path('orders/',include('orders.urls',namespace='orders')),
    path('payment/',include('payment.urls',namespace='payment')),
    path('login/',auth_views.LoginView.as_view(),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('register/', register, name='register'),
    path('',include('shop.urls',namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/',views.order_create,name='order_create'),
    path('admin/order/detail/<int:order_id>/',views.admin_order_detail,name='admin_order_detail'),
    path('admin/order/pdf/<int:order_id>/',views.admin_order_pdf,name='admin_order_pdf'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('',views.product_list,name='product_list'),
    path('<slug:category_slug>/',views.product_list,name='list_by_category'),
    path('detail/<int:id>/<slug:slug>/',views.product_detail,name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i,str(i)) for i in range(1,11)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
    update   = forms.BooleanField(initial=False,required=False,widget=forms.HiddenInput)   

cart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
# Create your views here.

def cart_add(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product,id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,quantity=cd['quantity'],update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product,id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity':item['quantity'],'update':True})
    return render(request,'cart/cart_detail.html',{'cart':cart})

cart/templates/cart/cart_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Cart|details
{% endblock %}
{% block content %}
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h2 class="display-4 mb-4">Your Cart :</h2>
      <table class="table table-striped text-center table-bordered">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Image</th>
            <th scope="col">Product</th>
            <th scope="col">Quantity</th>
            <th scope="col">Remove</th>
            <th scope="col">Unit Price</th>
            <th scope="col">Price</th>
          </tr>
        </thead>
        <tbody>
          {% for item in cart %}
            {% with p=item.product %}
              <tr scope="row">
                <td>
                  <a href="{{ p.get_absolute_url }}">
                    <img src="{% if p.image %}{{p.image.url}}{% else %}{% static 'no_image.jpeg' %}{%endif%}" width="100px" height="100px">
                  </a>
                </td>
                <td class="text-capitalize font-weight-bold">{{p.name}}</td>
                <td>
                  <form class="" action="{% url 'cart:cart_add' p.id %}" method="post">
                    {% csrf_token %}
                    {{item.update_quantity_form.quantity}}
                    {{item.update_quantity_form.update}}
                    <input type="submit" class="btn btn-info" value="Update">
                  </form>
                </td>
                <td><a href="{% url 'cart:cart_remove' p.id %}" class="text-danger font-weight-bold">Remove</a></td>
                <td>${{item.price}}</td>
                <td class="font-weight-bold">${{item.total_price}}</td>
              </tr>
            {% endwith %}
          {% endfor %}
          <tr class="bg-info" scope="row">
            <td class="font-weight-bold">Total:</td>
            <td colspan="4"></td>
            <td class="font-weight-bold">${{cart.get_total_price}}</td>
          </tr>
        </tbody>
      </table>
      <div class="mt-4">
        <p class="text-right">
          <a href="{% url 'shop:product_list' %}" class="btn btn-warning">Continue Shopping</a>
          <a href="{% url 'orders:order_create' %}" class="btn btn-success">Checkout</a>
        </p>
      </div>
    </div>
  </div>
{% endblock %}